In [1]:
import numpy as np

In [4]:
#1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.
arr1d = np.arange(0,30,).reshape(15,2)
arr1d

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [15]:
#2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
arr2d = np.random.randint(0, 101,60).reshape(3,-1,5)
print(arr2d)
print(arr2d.shape)
print(arr2d.ndim)

[[[ 89  82  51  64  51]
  [ 27  73  96  73  38]
  [ 95  10  55   8  64]
  [ 51  77  50  70  56]]

 [[  0  98   3  36  98]
  [ 70  31  60  27  61]
  [  2   8  17  21  22]
  [  3   3  40  31  95]]

 [[ 91  12  44  93  65]
  [ 20  74  94  17  60]
  [ 52 100  66  48  83]
  [ 31  44  46   4   6]]]
(3, 4, 5)
3


In [22]:
#3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
arr3d = np.random.randint(0,9,20).reshape(5,-1)
print(arr3d)
arr3d_duz = arr3d.reshape(-1)
arr3d_duz
print(arr3d_duz)
print(arr3d_duz.ndim)
print(arr3d_duz.shape)

[[0 6 5 3]
 [0 3 0 2]
 [8 5 4 8]
 [5 5 6 1]
 [2 2 8 6]]
[0 6 5 3 0 3 0 2 8 5 4 8 5 5 6 1 2 2 8 6]
1
(20,)


In [35]:
#4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.
arr4d = np.array([[2,4,6,8,10], [10,8,6,4,2]]) 
for x in arr4d:
  for y in x:
    print(y)
print("Finished with for(slow) method")
for x in np.nditer(arr4d):
  print(x)

2
4
6
8
10
10
8
6
4
2
Finished with for(slow) method
2
4
6
8
10
10
8
6
4
2


In [43]:
#5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
#   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
#   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.
arr5d = np.array([5,10,15,20,25,30])
arr5_2d = np.array([1,2,3,4,5,6])
arr5d.__add__(arr5_2d)

array([ 6, 12, 18, 24, 30, 36])

In [45]:
#6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.
arr6d = np.random.randint(0,100,10)
print(arr6d)
print(arr6d.sum())
print(arr6d.mean())
print(arr6d.max())
print(arr6d.var())
print(arr6d.std())


[42  1 33 42 45 74 12 45 34 30]
358
35.8
74
352.75999999999993
18.781906186540276


In [53]:
#7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.
arr7d = np.arange(20)
arr7_2d = np.arange(500,531)
print(arr7d)
print(arr7_2d)
print("Concatenate here:")
np.concatenate([arr7d,arr7_2d], axis=0)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517
 518 519 520 521 522 523 524 525 526 527 528 529 530]
Concatenate here:


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

In [63]:
#8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.
arr8d = np.arange(15,51)
arr8_2d = np.arange(10,101)
print("Concatenate type:")
arr8_3d = np.concatenate([arr8d, arr8_2d], axis = 0)
arr8_3d[25:51] = 888
print(arr8_3d)


Concatenate type:
[ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32
  33  34  35  36  37  38  39 888 888 888 888 888 888 888 888 888 888 888
 888 888 888 888 888 888 888 888 888 888 888 888 888 888 888  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


In [73]:
#9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.
arr9d = np.arange(0,40).reshape(8,5)
arr9_2d = np.arange(320,360).reshape(8,5)
print("Concatenate with axis=0")
print(np.concatenate([arr9d, arr9_2d], axis=0))
print("Concatenate with axis=1")
np.concatenate([arr9d, arr9_2d], axis=1)

Concatenate with axis=0
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [320 321 322 323 324]
 [325 326 327 328 329]
 [330 331 332 333 334]
 [335 336 337 338 339]
 [340 341 342 343 344]
 [345 346 347 348 349]
 [350 351 352 353 354]
 [355 356 357 358 359]]
Concatenate with axis=1


array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

In [76]:
#10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.
#CONCATENATE
np.concatenate([arr9d, arr9_2d], axis=2) #broken


AxisError: ignored

In [77]:
#10.2) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.
#STACK
np.stack([arr9d, arr9_2d], axis=2)

array([[[  0, 320],
        [  1, 321],
        [  2, 322],
        [  3, 323],
        [  4, 324]],

       [[  5, 325],
        [  6, 326],
        [  7, 327],
        [  8, 328],
        [  9, 329]],

       [[ 10, 330],
        [ 11, 331],
        [ 12, 332],
        [ 13, 333],
        [ 14, 334]],

       [[ 15, 335],
        [ 16, 336],
        [ 17, 337],
        [ 18, 338],
        [ 19, 339]],

       [[ 20, 340],
        [ 21, 341],
        [ 22, 342],
        [ 23, 343],
        [ 24, 344]],

       [[ 25, 345],
        [ 26, 346],
        [ 27, 347],
        [ 28, 348],
        [ 29, 349]],

       [[ 30, 350],
        [ 31, 351],
        [ 32, 352],
        [ 33, 353],
        [ 34, 354]],

       [[ 35, 355],
        [ 36, 356],
        [ 37, 357],
        [ 38, 358],
        [ 39, 359]]])

In [78]:
#11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.
arr11d = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
np.where(arr11d == 5)



(array([ 5, 13]),)

In [83]:
#12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.
np.where(arr11d%2 == 0)

(array([ 1,  3,  4,  6,  7,  9, 11]),)

In [84]:
#13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.
np.where(arr11d > 4)

(array([ 1,  2,  5,  9, 10, 11, 13]),)

In [85]:
#14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.
np.where(arr11d%5 == 0)

(array([ 1,  2,  5, 13]),)

In [119]:
#15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin
arr15d = np.random.randint(85, 101,1)
arr15d
np.random.choice(arr15d)

98

In [125]:
#16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.
arr16d = np.random.randint(10,100,(3,3))
arr16d


array([[21, 73, 94],
       [97, 26, 40],
       [24, 58, 98]])

In [127]:
#17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.
arr17d = np.arange(35,61)
arr17d
np.random.choice(arr17d)

42

In [138]:
#18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.(YAPAMADIM)
arr18d = np.array([[3,8,10,53], [3,8,10,53]]).reshape(2,5)
arr18d

ValueError: ignored